name: Pylint

on: [push]

jobs:
  pylint:
    name: pylint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Pylint action
      uses: cclauss/GitHub-Action-for-pylint@master
      with:
        args: "pip install -r requirements.txt ; pylint $(find . -name *.py)"
